const input=document.querySelector('#imageInput'),preview=document.querySelector('#preview'),empty=document.querySelector('#emptyState'),remove=document.querySelector('#removeImage'),button=document.querySelector('#searchButton'),error=document.querySelector('#fileError'),drop=document.querySelector('#dropZone'),loading=document.querySelector('#loading'),results=document.querySelector('#results');
const palette={RED:'#d52f3d',MAROON:'#761d36',PINK:'#e8789e',ORANGE:'#ed8533',YELLOW:'#e2b62c',GOLD:'#bc913d',GREEN:'#388c57',DARK_GREEN:'#1f593b',BLUE:'#397cc4',NAVY_BLUE:'#203e73',PURPLE:'#77509b',VIOLET:'#a45ca9',BLACK:'#272228',WHITE:'#fff',GREY:'#8d8e92',SILVER:'#b7b9bc',BROWN:'#80563d',BEIGE:'#c8a77e',CREAM:'#eee1be'};
const catalog=window.SAREE_CATALOG||[];let selected;document.querySelector('#catalogStatus').textContent=catalog.length?`${catalog.length} sarees indexed and ready to match`:'The saree collection is unavailable.';
function setImage(file){error.textContent='';if(!file)return;if(!['image/jpeg','image/png'].includes(file.type)){error.textContent='Please upload a valid JPG, JPEG, or PNG image.';return}if(file.size>10*1024*1024){error.textContent='Image must be 10 MB or smaller.';return}selected=file;preview.src=URL.createObjectURL(file);preview.style.display='block';empty.style.display='none';remove.style.display='block';button.disabled=!catalog.length}
input.addEventListener('change',()=>setImage(input.files[0]));remove.addEventListener('click',e=>{e.preventDefault();selected=null;input.value='';preview.removeAttribute('src');preview.style.display='none';empty.style.display='grid';remove.style.display='none';button.disabled=true;results.classList.add('hidden')});['dragenter','dragover'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>setImage(e.dataTransfer.files[0]));
button.addEventListener('click',async()=>{if(!selected)return;loading.classList.remove('hidden');results.classList.add('hidden');button.disabled=true;error.textContent='';try{const colors=await analyse(selected);const matches=catalog.map(s=>({...s,similarity:score(colors,s.color)})).filter(s=>s.similarity>=42).sort((a,b)=>b.similarity-a.similarity).slice(0,24);render({matched:matches.length>0,totalMatches:matches.length,detectedColors:colors,matches})}catch(e){error.textContent='This image could not be analysed. Please choose another JPG, JPEG, or PNG image.'}finally{loading.classList.add('hidden');button.disabled=false}});
async function analyse(file){const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0,100,100);const pixels=ctx.getImageData(0,0,100,100).data,counts={};for(let i=0;i<pixels.length;i+=16){const name=classify(pixels[i],pixels[i+1],pixels[i+2]);counts[name]=(counts[name]||0)+1}const all=Object.values(counts).reduce((a,b)=>a+b,0);return Object.entries(counts).map(([color,n])=>({color,percentage:Math.round(n*1000/all)/10})).filter(x=>x.percentage>=4).sort((a,b)=>b.percentage-a.percentage).slice(0,3)}
function classify(r,g,b){const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0,s=max?d/max:0;if(max===r&&d)h=((g-b)/d+6)%6;else if(max===g&&d)h=(b-r)/d+2;else if(d)h=(r-g)/d+4;h*=60;if(max<48)return'BLACK';if(s<.1)return max>220?'WHITE':max>165?'SILVER':'GREY';if(max>205&&s<.32)return'CREAM';if(h>=8&&h<40&&max<145)return'BROWN';if(h>=35&&h<58&&s<.62)return'GOLD';if(h>=20&&h<42)return'ORANGE';if(h>=42&&h<70)return'YELLOW';if(h>=70&&h<165)return max<130?'DARK_GREEN':'GREEN';if(h>=165&&h<245)return max<125?'NAVY_BLUE':'BLUE';if(h>=245&&h<285)return'PURPLE';if(h>=285&&h<325)return'VIOLET';if((h>=325||h<12)&&max<135)return'MAROON';if((h>=325||h<12)&&s<.68)return'PINK';return'RED'}
function score(colors,target){const q=colors[0];if(!q)return 0;if(q.color===target)return Math.min(99,72+q.percentage*.27);const near={RED:['MAROON','PINK','ORANGE'],MAROON:['RED','PINK','BROWN'],PINK:['RED','MAROON','VIOLET'],ORANGE:['GOLD','YELLOW','RED','BROWN'],GOLD:['YELLOW','ORANGE','BEIGE','CREAM'],BLACK:['GREY','SILVER'],GREY:['BLACK','SILVER','WHITE'],SILVER:['GREY','WHITE','BLACK']};if((near[q.color]||[]).includes(target))return 45+q.percentage*.18;for(const c of colors.slice(1))if(c.color===target)return 40+c.percentage*.28;return 0}
function pretty(c){return c.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,x=>x.toUpperCase())}function render(data){document.querySelector('#colors').innerHTML=data.detectedColors.map(c=>`<span class="chip"><i class="dot" style="background:${palette[c.color]||'#888'}"></i>${pretty(c.color)} <b>${c.percentage}%</b></span>`).join('');document.querySelector('#count').textContent=data.totalMatches;document.querySelector('.match-count span').textContent=`matching saree${data.totalMatches===1?'':'s'} found`;const no=document.querySelector('#noMatch'),gallery=document.querySelector('#gallery');no.classList.toggle('hidden',data.matched);gallery.innerHTML=data.matches.map(m=>`<article class="card"><img src="${m.imagePath}" alt="${m.imageName}"><div class="card-body"><h3>${m.imageName.split('/').pop()}</h3><div class="score"><span>${pretty(m.color)}</span><b>${m.similarity.toFixed(1)}% match</b></div></div></article>`).join('');results.classList.remove('hidden');results.scrollIntoView({behavior:'smooth',block:'start'})}

